version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/" 
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "mazharenko.AoCAgent"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "monthly"
